config/routes.rb
Cfg::Application.routes.draw do
  

  get "items/all"

  get "items/broken"

  get "items/returnable"


  get '/api/tools_by_location/:id', to: 'api#tools_by_location'
  get '/api/qr/:id', to: 'api#qr'


  match 'api/new_item' => 'api#new_item', :via => :post
  match 'api/check_out' => 'api#check_out', :via => :post
  match 'api/check_in' => 'api#check_in', :via => :post


  resources :locations

  resources :items


  devise_for :users

  get "main/hello"
  get "getuser/index"

root :to => "locations#index"
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def all
  	@tools = Tool.all

  	respond_to do |format|
      format.html  #index.html.erb
      format.json { render :json => @tools }
    end
  end

  def broken
  	@tools = Tool.where(working: false)
  	respond_to do |format|
      format.html  #index.html.erb
      format.json { render :json => @tools }
    end

  end

  def returnable
  	@tools = Tool.where(returnable: true)
  	respond_to do |format|
      format.html  #index.html.erb
      format.json { render :json => @tools }
    end
  end

  def show
    @tools = Tool.find(params[:id])

    respond_to do |format|
      format.html  #show.html.erb
      format.json { render :json => @location }
    end
  end

  def destroy
    @tool = Tool.find(params[:id])
    @tool.destroy

    respond_to do |format|
      format.html { redirect_to :action => 'all' }
      format.json { head :no_content }
    end
  end

end

app/views/items/_form.html.erb
<table width=600>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Status</th>
    <th></th>
    <th>Return Date</th>
    <th></th>
    <th></th>
  </tr>

<% @tools.each do |tool| %>
  <tr>
    <td><%= tool.name %></td>
    <td><%= Location.find(tool.location_id).name %></td>
    <td>
    <% if tool.working == true %>
      Working
    <% else %>
      Broken
    <% end %>
    </td>
    <td>
    <% if tool.checked_out == true %>
      Checked Out
    <% else %>
      In Base
    <% end %>
    </td>

    <td><%= tool.return_date %>
    <td><%= link_to 'Show', tool.id.to_s %></td>
    <td><%= link_to 'Delete', tool.id.to_s, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/items/all.html.erb
<h1>All Items</h1>
<%= render 'form' %>

app/views/items/broken.html.erb
<h1>Broken Items</h1>
<%= render 'form' %>

app/views/items/returnable.html.erb
<h1>Returnable Items</h1>
<%= render 'form' %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tools.name %><br>
  <b>Status:</b>
  <% if @tools.checked_out == true %>
    Checked Out
  <% else %>
    At Base
  <% end %><br>
  <b>Donor:</b>
  <%= @tools.donor %><br>
  <b>Donor Email:</b>
  <%= @tools.donor_email %><br>
  <b>QR Code:</b>
  <%= @tools.qr_code %><br>
  <b>Category:</b>
  <%= @tools.category %><br>
  <b>Working Status:</b>
  <% if @tools.working == true%>
    Working
  <% else %>
    Broken
  <% end %><br>
  <% if @tools.returnable == true %>
  <b>Return Date:</b>
    <%= @tools.return_date %><br>
  <% end %>
  <b>Location ID:</b>
  <%= @tools.location_id %><br>
  <b>Location Name:</b>
  <%= Location.find(@tools.location_id).name %><br>
  <% if @tools.working == false %>
    <b>Broken Description:</b>
    <%= @tools.broken_description %>
  <% end %>
</p>

<%= link_to 'Back', items_all_path %>